#!/usr/bin/env bash
if [ "$1" == "run_prod" ]; then
  rm -rf _build
  rm -rf cover
  rm -rf deps
  mix local.hex --force
  mix local.rebar --force

  mix deps.get --only prod
  MIX_ENV=prod mix compile
  # Custom tasks (like DB migrations)
  MIX_ENV=prod mix ecto.setup
  # Finally run the server in detached mode in order to close the console
  MIX_ENV=prod mix phx.server
  trap : TERM INT; sleep infinity & wait
else
  sh -c "$@"
fi